version: '3'

services:
    db:
        # build: ./mysql/
        image: mysql-con
        container_name: mysql-con
        # ports:
        #     - 3306:3306
        restart: always
        
    wordpress:
        # build: ./wordpress/
        image: wp
        container_name: wp
        ports:
            - 8080:80
        depends_on:
            - db
        restart: always